-- Migration: chat_messages (applied 2026-09-08 to project afxsoxexfahehhjijzlr)
--
-- Party chat for the Kansai Quest map. Append-only: anon may read everything and
-- insert, but never update or delete — same posture as `reactions`.
-- Earlier migrations are recorded in supabase-setup.sql.

create table if not exists public.chat_messages (
  id          bigint generated by default as identity primary key,
  player_id   text not null,
  player_name text,
  av          integer default 0,
  body        text not null,
  lat         double precision,
  lng         double precision,
  ts          bigint not null,
  created_at  timestamptz not null default now()
);

create index if not exists chat_messages_ts_idx on public.chat_messages (ts);

alter table public.chat_messages enable row level security;

drop policy if exists "chat read for all" on public.chat_messages;
create policy "chat read for all" on public.chat_messages
  for select to anon, authenticated using (true);

drop policy if exists "chat insert for all" on public.chat_messages;
create policy "chat insert for all" on public.chat_messages
  for insert to anon, authenticated
  with check (char_length(body) between 1 and 240);
